# Generated by Django 4.2.5 on 2023-09-15 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_by_creator', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024),
        ),
        migrations.AddField(
            model_name='course',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_by_last_editor', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='course',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='homework',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_by_creator', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024),
        ),
        migrations.AddField(
            model_name='homework',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_by_last_editor', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='homework',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='homework',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_by_creator', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_by_last_editor', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='step',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_by_creator', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024),
        ),
        migrations.AddField(
            model_name='step',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_by_last_editor', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='step',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_by_creator', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024),
        ),
        migrations.AddField(
            model_name='task',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_by_last_editor', to='extended_user.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='task',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='password',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
