# Generated by Django 4.2.5 on 2023-09-25 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
        ('course', '0002_course_creator_course_description_course_last_editor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegOnCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Обратная связь')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='regs_by_course', to='course.course', verbose_name='Курс')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='regs_by_student', to='extended_user.profile', verbose_name='Студент')),
            ],
        ),
    ]
