# Generated by Django 4.2.5 on 2023-11-04 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_rename_edges_count_graph_nodes_count'),
        ('extended_user', '0001_initial'),
        ('course', '0004_alter_course_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.graph', verbose_name='Иллюстрация к шагу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_by_creator', to='extended_user.profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='editors',
            field=models.ManyToManyField(to='extended_user.profile', verbose_name='Редакторы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_by_last_editor', to='extended_user.profile', verbose_name='Последний редактор'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=1024, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='password',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='course',
            name='private',
            field=models.BooleanField(default=False, verbose_name='С ограниченным доступом'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Последнее редактирование'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_by_creator', to='extended_user.profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_by_last_editor', to='extended_user.profile', verbose_name='Последний редактор'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='mark',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='name',
            field=models.CharField(max_length=1024, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='course.step', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Последнее редактирование'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_by_creator', to='extended_user.profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_by_last_editor', to='extended_user.profile', verbose_name='Последний редактор'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=1024, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Последнее редактирование'),
        ),
        migrations.AlterField(
            model_name='step',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_by_creator', to='extended_user.profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='step',
            name='data',
            field=martor.models.MartorField(verbose_name='Материалы шага'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='step',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_by_last_editor', to='extended_user.profile', verbose_name='Последний редактор'),
        ),
        migrations.AlterField(
            model_name='step',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='course.lesson', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=1024, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='step',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='step',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Последнее редактирование'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_by_creator', to='extended_user.profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='Описание не заполнено', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_by_last_editor', to='extended_user.profile', verbose_name='Последний редактор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_mark',
            field=models.IntegerField(verbose_name='Максимальная оценка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=1024, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='course.step', verbose_name='Шаг'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_create',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_edit',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Последнее редактирование'),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.IntegerField(default=10, verbose_name='Вес оценки'),
        ),
    ]
