# Generated by Django 4.2.5 on 2023-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_step_graph_alter_course_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_test',
            field=models.BooleanField(default=False, verbose_name='Автоматическая проверка'),
        ),
        migrations.AddField(
            model_name='task',
            name='correct_answers',
            field=models.TextField(blank=True, null=True, verbose_name='Правильные ответы (варианты через ;)'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True, default='Описание не заполнено', max_length=1024, null=True, verbose_name='Описание'),
        ),
    ]
