# Generated by Django 4.2.5 on 2023-11-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_rename_edges_count_graph_nodes_count'),
        ('course', '0006_task_auto_test_task_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.graph', verbose_name='Иллюстрация к заданию'),
        ),
    ]
