# Generated by Django 4.2.5 on 2023-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_task_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='Описание не заполнено', max_length=4096, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='Описание не заполнено', max_length=4096, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(default='Описание не заполнено', max_length=4096, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='Описание не заполнено', max_length=4096, verbose_name='Описание'),
        ),
    ]
