# Generated by Django 4.2.5 on 2023-11-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='course.task', verbose_name='Задание'),
        ),
    ]
