# Generated by Django 4.2.5 on 2023-11-10 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
        ('course', '0009_alter_homework_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_by_last_editor', to='extended_user.profile', verbose_name='Проверяющий'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='mark',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
