# Generated by Django 4.2.5 on 2023-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_homework_last_editor_alter_homework_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(max_length=1024, null=True, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название'),
        ),
    ]
