# Generated by Django 4.2.5 on 2024-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_homework_description_alter_homework_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_edit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последнее редактирование'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='time_edit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последнее редактирование'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_edit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последнее редактирование'),
        ),
        migrations.AlterField(
            model_name='step',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='step',
            name='time_edit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последнее редактирование'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_edit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последнее редактирование'),
        ),
    ]
