# Generated by Django 4.2.5 on 2023-11-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='directed',
            field=models.BooleanField(default=False, verbose_name='Ориентированный граф'),
        ),
    ]
