# Generated by Django 4.2.5 on 2023-11-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_graph_edges_count_alter_graph_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='edges_count',
            new_name='nodes_count',
        ),
    ]
