# Generated by Django 4.2.5 on 2024-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_rename_edges_count_graph_nodes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
